#!/bin/sh
set -e
if [ "$1" = "remove" ] || [ "$1" = "purge" ]; then
    rm -rf /usr/share/awg-manager/awgmanager/__pycache__ 2>/dev/null || true
    if which gtk-update-icon-cache >/dev/null 2>&1; then
        gtk-update-icon-cache -qtf /usr/share/icons/hicolor 2>/dev/null || true
    fi
fi
exit 0
